version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: boss-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ~/docker-volumes/boss/zookeeper-data/data:/data
      - ~/docker-volumes/boss/zookeeper-data/datalog:/datalog
    networks:
      default:
        ipv4_address: ${MAX_ZOOKEEPER_HOST}
  kafka:
    build: .
    container_name: boss-kafka
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT: ${KAFKA_ADVERTISED_PORT}
      KAFKA_ZOOKEEPER_CONNECT: ${MAX_ZOOKEEPER_HOST}:2181
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_DELETE_TOPIC_ENABLE: ${KAFKA_DELETE_TOPIC_ENABLE}
      KAFKA_LOG_CLEANER_ENABLE: ${KAFKA_LOG_CLEANER_ENABLE}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - ~/docker-volumes/boss/kafka-data/logs:/app/kafka/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: ${MAX_KAFKA_HOST}

networks:
  default:
    name: ${MAX_NETWORK}
    external: true